"""P2 tab ④ insight repository: immutable ``insight.v1`` storage, import, reads."""

from __future__ import annotations

from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path
from typing import Any

import httpx
import pytest
import yaml

from futures_research.api.main import app
from futures_research.insight.store import InsightStore
from futures_research.sketch.store import SketchStore

PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"
CHART_FILES = ("chart-D.png", "chart-1H.png", "chart-30m.png", "chart-5m.png")

# Hand-authored against docs/05 §3.5.1 — never generated by the code under test.
INSIGHT_YAML = """\
schema: insight.v1
insight_id: insight-007
origin: workshop
version: 1
based_on_sketch: sketch-20260725-02
based_on_sketch_origin: workshop
instrument: NQ
asset_class: equity_index_futures
title: 開市頭30分鐘假突破多
condition:
  type: session_time_filter
  suggested_params: {skip_first_minutes: 30}
measurement:
  tag: entry_within_open_30m
  hypothesis: 呢類入市嘅期望值顯著低過其他時段
validation_status: unverified
"""

SKETCH_META = """\
schema: sketch.v1
sketch_id: sketch-20260725-02
kind: insight
origin: workshop
chart_source: screenshot
instructions_template: instructions.v1
instrument: NQ
asset_class: equity_index_futures
created: 2026-07-25
title: 開市頭 30 分鐘觀察
charts:
  - file: chart-D.png
    timeframe: D
    indicators_shown: [ema18]
    owner_view: 日線只作背景。
  - file: chart-1H.png
    timeframe: 1H
    indicators_shown: [ema18]
    owner_view: 1H 觀察開市段落。
  - file: chart-30m.png
    timeframe: 30m
    indicators_shown: []
    owner_view: 30m 見到假突破。
  - file: chart-5m.png
    timeframe: 5m
    indicators_shown: [ema18]
    owner_view: 5m 逐根睇。
"""

SKETCH_INSTRUCTIONS = "<!-- instructions.v1 -->\n# 指令書\n\n讀四張圖再量化。\n"


def _replace(source: str, old: str, new: str) -> str:
    """Fail loudly instead of silently producing an unchanged fixture."""
    if old not in source:
        msg = f"fixture does not contain {old!r}"
        raise AssertionError(msg)
    return source.replace(old, new)


def _drop_line(source: str, needle: str) -> str:
    kept = [line for line in source.splitlines(keepends=True) if needle not in line]
    if len(kept) == len(source.splitlines(keepends=True)):
        msg = f"fixture does not contain a line with {needle!r}"
        raise AssertionError(msg)
    return "".join(kept)


def _store(tmp_path: Path, *, with_sketch: bool = False, **sketch_fields: str) -> InsightStore:
    sketch_root = tmp_path / "sketches"
    sketch_root.mkdir(parents=True, exist_ok=True)
    if with_sketch:
        _write_sketch(sketch_root, **sketch_fields)
    return InsightStore(
        root=tmp_path / "insights",
        sketch_store=SketchStore(root=sketch_root),
    )


def _write_sketch(
    sketch_root: Path,
    *,
    instrument: str = "NQ",
    asset_class: str = "equity_index_futures",
) -> Path:
    meta = _replace(SKETCH_META, "instrument: NQ", f"instrument: {instrument}")
    meta = _replace(
        meta,
        "asset_class: equity_index_futures",
        f"asset_class: {asset_class}",
    )
    folder = sketch_root / "workshop" / "sketch-20260725-02"
    folder.mkdir(parents=True)
    (folder / "meta.yaml").write_text(meta, encoding="utf-8")
    (folder / "INSTRUCTIONS.md").write_text(SKETCH_INSTRUCTIONS, encoding="utf-8")
    for filename in CHART_FILES:
        (folder / filename).write_bytes(PNG_SIGNATURE + filename.encode("utf-8"))
    return folder


@contextmanager
def _api_dependency(store: InsightStore) -> Iterator[None]:
    """Install a temp production store and restore any prior app state."""
    missing = object()
    prior = getattr(app.state, "insight_store", missing)
    app.state.insight_store = store
    try:
        yield
    finally:
        if prior is missing:
            delattr(app.state, "insight_store")
        else:
            app.state.insight_store = prior


def _file_inventory(root: Path) -> dict[str, bytes]:
    if not root.exists():
        return {}
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def _directory_inventory(root: Path) -> list[str]:
    if not root.exists():
        return []
    return sorted(
        path.relative_to(root).as_posix() for path in root.rglob("*") if path.is_dir()
    )


@contextmanager
def _client() -> Iterator[httpx.AsyncClient]:
    transport = httpx.ASGITransport(app=app)
    yield httpx.AsyncClient(transport=transport, base_url="http://test")


async def _import(client: httpx.AsyncClient, source_text: str) -> httpx.Response:
    return await client.post(
        "/api/v1/insights/import",
        json={"source_text": source_text},
    )


@pytest.mark.asyncio
async def test_import_stores_verbatim_source_and_reads_back_exactly(tmp_path: Path) -> None:
    store = _store(tmp_path)
    with _api_dependency(store), _client() as client:
        async with client:
            created = await _import(client, INSIGHT_YAML)
            listed = await client.get("/api/v1/insights")
            detail = await client.get("/api/v1/insights/workshop/insight-007")

    assert created.status_code == 200
    body = created.json()
    assert body["schema"] == "insight_import.v1"
    assert body["deduplicated"] is False
    record = body["insight"]
    assert record["schema"] == "insight_version.v1"
    assert record["insight_id"] == "insight-007"
    assert record["origin"] == "workshop"
    assert record["version"] == 1
    assert record["title"] == "開市頭30分鐘假突破多"
    assert record["instrument"] == "NQ"
    assert record["asset_class"] == "equity_index_futures"
    assert record["tag"] == "entry_within_open_30m"
    assert record["validation_status"] == "unverified"
    assert record["based_on_sketch"] == "sketch-20260725-02"
    assert record["based_on_sketch_origin"] == "workshop"
    assert record["imported_from_origin"] is None
    assert record["source_text"] == INSIGHT_YAML
    assert record["imported_at"].endswith("Z")

    stored = store.root / "workshop" / "insight-007" / "v1.yaml"
    assert stored.is_file()
    payload = yaml.safe_load(stored.read_text(encoding="utf-8"))
    assert payload["source_text"] == INSIGHT_YAML

    assert listed.status_code == 200
    listing = listed.json()
    assert listing["schema"] == "insight_list.v1"
    assert listing["count"] == 1
    summary = listing["insights"][0]
    assert summary["versions"] == [1]
    assert summary["latest_version"] == 1
    assert "source_text" not in summary

    assert detail.status_code == 200
    detail_body = detail.json()
    assert detail_body["schema"] == "insight_detail.v1"
    assert detail_body["version_count"] == 1
    assert detail_body["versions"][0]["source_text"] == INSIGHT_YAML


@pytest.mark.asyncio
async def test_complete_lineage_without_local_sketch_is_accepted(tmp_path: Path) -> None:
    """Provenance is a declaration; a missing local package is not an error."""
    store = _store(tmp_path)
    with _api_dependency(store), _client() as client:
        async with client:
            response = await _import(client, INSIGHT_YAML)

    assert response.status_code == 200
    assert response.json()["insight"]["based_on_sketch"] == "sketch-20260725-02"


@pytest.mark.asyncio
async def test_incomplete_or_invalid_lineage_is_rejected_without_writing(
    tmp_path: Path,
) -> None:
    store = _store(tmp_path)
    invalid_sources = [
        _drop_line(INSIGHT_YAML, "based_on_sketch_origin:"),
        _drop_line(INSIGHT_YAML, "based_on_sketch:"),
        _replace(INSIGHT_YAML, "based_on_sketch_origin: workshop", "based_on_sketch_origin:"),
        _replace(INSIGHT_YAML, "based_on_sketch_origin: workshop", "based_on_sketch_origin: ''"),
        _replace(INSIGHT_YAML, "based_on_sketch_origin: workshop", "based_on_sketch_origin: js"),
        _replace(INSIGHT_YAML, "based_on_sketch: sketch-20260725-02", "based_on_sketch: null"),
        _replace(INSIGHT_YAML, "based_on_sketch: sketch-20260725-02", "based_on_sketch: 20260725"),
        _replace(
            INSIGHT_YAML,
            "based_on_sketch: sketch-20260725-02",
            "based_on_sketch: sketch-20261325-02",
        ),
    ]
    with _api_dependency(store), _client() as client:
        async with client:
            for source in invalid_sources:
                response = await _import(client, source)
                assert response.status_code == 422, source
                detail = response.json()["detail"]
                assert detail["schema"] == "insight_validation.v1"
                assert detail["issue_count"] >= 1
                assert detail["report_text"]

    assert _file_inventory(store.root) == {}


@pytest.mark.asyncio
async def test_instrument_identity_must_match_catalog_and_local_sketch(
    tmp_path: Path,
) -> None:
    unknown_symbol = _replace(INSIGHT_YAML, "instrument: NQ", "instrument: XYZ")
    class_drift = _replace(
        INSIGHT_YAML,
        "asset_class: equity_index_futures",
        "asset_class: commodity_futures",
    )
    missing_instrument = _drop_line(INSIGHT_YAML, "instrument:")
    missing_class = _drop_line(INSIGHT_YAML, "asset_class:")

    catalog_store = _store(tmp_path / "catalog")
    with _api_dependency(catalog_store), _client() as client:
        async with client:
            for source in (unknown_symbol, class_drift, missing_instrument, missing_class):
                response = await _import(client, source)
                assert response.status_code == 422, source
    assert _file_inventory(catalog_store.root) == {}

    # Same document, but the referenced package on this machine is a GC sketch.
    sketch_store = _store(tmp_path / "sketch", with_sketch=True, instrument="GC")
    with _api_dependency(sketch_store), _client() as client:
        async with client:
            response = await _import(client, INSIGHT_YAML)
    assert response.status_code == 422
    lines = response.json()["detail"]["report_text"]
    assert "local sketch instrument" in lines
    assert _file_inventory(sketch_store.root) == {}

    matching_store = _store(tmp_path / "match", with_sketch=True)
    with _api_dependency(matching_store), _client() as client:
        async with client:
            response = await _import(client, INSIGHT_YAML)
    assert response.status_code == 200


@pytest.mark.asyncio
async def test_identical_retry_deduplicates_and_content_drift_never_overwrites(
    tmp_path: Path,
) -> None:
    store = _store(tmp_path)
    drifted = _replace(INSIGHT_YAML, "title: 開市頭30分鐘假突破多", "title: 改咗個名")
    with _api_dependency(store), _client() as client:
        async with client:
            first = await _import(client, INSIGHT_YAML)
            after_first = _file_inventory(store.root)
            retry = await _import(client, INSIGHT_YAML)
            conflict = await _import(client, drifted)

    assert first.status_code == 200
    assert first.json()["deduplicated"] is False
    assert retry.status_code == 200
    assert retry.json()["deduplicated"] is True
    assert retry.json()["insight"] == first.json()["insight"]
    assert conflict.status_code == 409
    assert conflict.json()["detail"]["schema"] == "insight_import_conflict.v1"
    assert _file_inventory(store.root) == after_first


@pytest.mark.asyncio
async def test_external_copy_missing_earlier_versions_is_accepted_and_flagged(
    tmp_path: Path,
) -> None:
    store = _store(tmp_path)
    only_v2 = _replace(INSIGHT_YAML, "version: 1", "version: 2")
    with _api_dependency(store), _client() as client:
        async with client:
            response = await _import(client, only_v2)
            listed = await client.get("/api/v1/insights")

    assert response.status_code == 200
    record = response.json()["insight"]
    assert record["version"] == 2
    assert record["imported_from_origin"] == "workshop"
    assert listed.json()["insights"][0]["versions"] == [2]
    assert (store.root / "workshop" / "insight-007" / "v2.yaml").is_file()
    assert not (store.root / "workshop" / "insight-007" / "v1.yaml").exists()


@pytest.mark.asyncio
async def test_new_version_never_rewrites_the_previous_version_bytes(
    tmp_path: Path,
) -> None:
    store = _store(tmp_path)
    second = _replace(INSIGHT_YAML, "version: 1", "version: 2")
    second = _replace(second, "validation_status: unverified", "validation_status: recording")
    with _api_dependency(store), _client() as client:
        async with client:
            await _import(client, INSIGHT_YAML)
            first_bytes = (store.root / "workshop" / "insight-007" / "v1.yaml").read_bytes()
            await _import(client, second)
            detail = await client.get("/api/v1/insights/workshop/insight-007")
            listed = await client.get("/api/v1/insights")

    assert (store.root / "workshop" / "insight-007" / "v1.yaml").read_bytes() == first_bytes
    body = detail.json()
    assert [version["version"] for version in body["versions"]] == [1, 2]
    assert body["versions"][0]["source_text"] == INSIGHT_YAML
    assert body["versions"][1]["source_text"] == second
    assert body["versions"][0]["validation_status"] == "unverified"
    assert body["latest_version"] == 2
    summary = listed.json()["insights"][0]
    assert summary["versions"] == [1, 2]
    assert summary["validation_status"] == "recording"


@pytest.mark.asyncio
async def test_publication_failure_writes_nothing_and_reports_sanitized_503(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    store = _store(tmp_path)
    before_files = _file_inventory(store.root)
    before_dirs = _directory_inventory(store.root)

    def fail_link(_temporary: Path, _target: Path) -> None:
        raise OSError("injected C:/secret/insight publication failure")

    monkeypatch.setattr(InsightStore, "_link_version", staticmethod(fail_link))
    with _api_dependency(store), _client() as client:
        async with client:
            response = await _import(client, INSIGHT_YAML)
            listed = await client.get("/api/v1/insights")

    assert response.status_code == 503
    assert "C:/secret" not in response.text
    assert "injected" not in response.text
    assert _file_inventory(store.root) == before_files
    assert _directory_inventory(store.root) == before_dirs
    assert not list(store.root.rglob("*.tmp")) if store.root.exists() else True
    assert listed.json()["count"] == 0


@pytest.mark.asyncio
async def test_composite_identity_lets_two_origins_share_one_insight_number(
    tmp_path: Path,
) -> None:
    store = _store(tmp_path)
    journal = _replace(INSIGHT_YAML, "\norigin: workshop", "\norigin: journal-app")
    journal = _replace(
        journal,
        "based_on_sketch_origin: workshop",
        "based_on_sketch_origin: journal-app",
    )
    journal = _replace(journal, "title: 開市頭30分鐘假突破多", "title: 日記 app 嘅同號洞察")
    with _api_dependency(store), _client() as client:
        async with client:
            first = await _import(client, INSIGHT_YAML)
            second = await _import(client, journal)
            listed = await client.get("/api/v1/insights")
            workshop_detail = await client.get("/api/v1/insights/workshop/insight-007")
            journal_detail = await client.get("/api/v1/insights/journal-app/insight-007")

    assert first.status_code == 200
    assert second.status_code == 200
    assert second.json()["deduplicated"] is False
    assert listed.json()["count"] == 2
    assert {summary["origin"] for summary in listed.json()["insights"]} == {
        "workshop",
        "journal-app",
    }
    assert workshop_detail.json()["versions"][0]["source_text"] == INSIGHT_YAML
    assert journal_detail.json()["versions"][0]["source_text"] == journal


@pytest.mark.asyncio
async def test_unknown_identity_and_malformed_request_are_rejected(tmp_path: Path) -> None:
    store = _store(tmp_path)
    with _api_dependency(store), _client() as client:
        async with client:
            unknown = await client.get("/api/v1/insights/workshop/insight-999")
            bad_origin = await client.get("/api/v1/insights/nowhere/insight-007")
            bad_id = await client.get("/api/v1/insights/workshop/insight-7")
            extra_field = await client.post(
                "/api/v1/insights/import",
                json={"source_text": INSIGHT_YAML, "origin": "workshop"},
            )
            empty_body = await client.post("/api/v1/insights/import", json={"source_text": ""})
            not_a_mapping = await _import(client, "- 唔係 mapping\n")
            broken_yaml = await _import(client, "schema: insight.v1\n  bad: [\n")

    assert unknown.status_code == 404
    assert bad_origin.status_code == 404
    assert bad_id.status_code == 404
    assert extra_field.status_code == 422
    assert empty_body.status_code == 422
    assert not_a_mapping.status_code == 422
    assert broken_yaml.status_code == 422
    assert _file_inventory(store.root) == {}


@pytest.mark.asyncio
async def test_document_level_gates_reject_unknown_fields_and_values(
    tmp_path: Path,
) -> None:
    store = _store(tmp_path)
    invalid_sources = [
        _replace(INSIGHT_YAML, "schema: insight.v1", "schema: insight.v2"),
        _replace(INSIGHT_YAML, "insight_id: insight-007", "insight_id: insight-7"),
        _replace(INSIGHT_YAML, "insight_id: insight-007", "insight_id: ' insight-007'"),
        _replace(INSIGHT_YAML, "version: 1", "version: 0"),
        _replace(INSIGHT_YAML, "version: 1", "version: true"),
        _replace(INSIGHT_YAML, "version: 1", "version: '1'"),
        _replace(INSIGHT_YAML, "validation_status: unverified", "validation_status: pending"),
        _replace(INSIGHT_YAML, "title: 開市頭30分鐘假突破多", "title: ''"),
        _drop_line(INSIGHT_YAML, "  tag:"),
        _drop_line(INSIGHT_YAML, "  hypothesis:"),
        _drop_line(INSIGHT_YAML, "  type: session_time_filter"),
        INSIGHT_YAML + "based_on_insights: [insight-006]\n",
        _replace(
            INSIGHT_YAML,
            "  suggested_params: {skip_first_minutes: 30}",
            "  suggested_params:",
        ),
    ]
    with _api_dependency(store), _client() as client:
        async with client:
            for source in invalid_sources:
                response = await _import(client, source)
                assert response.status_code == 422, source

    assert _file_inventory(store.root) == {}


@pytest.mark.asyncio
async def test_repository_exposes_only_recoverable_archive_mutation(
    tmp_path: Path,
) -> None:
    """P2 #22/#23: archive is allowed; status flips and run linkage remain absent."""
    store = _store(tmp_path)
    with _api_dependency(store), _client() as client:
        async with client:
            await _import(client, INSIGHT_YAML)
            archive = await client.delete("/api/v1/insights/workshop/insight-007")
            patch = await client.patch(
                "/api/v1/insights/workshop/insight-007",
                json={"validation_status": "supported"},
            )
            archives = await client.get("/api/v1/insights/archives")

    assert archive.status_code == 200
    assert patch.status_code == 405
    assert archives.json()["count"] == 1
    published = {
        path: sorted(operations)
        for path, operations in app.openapi()["paths"].items()
        if path.startswith("/api/v1/insights")
    }
    assert published == {
        "/api/v1/insights": ["get"],
        "/api/v1/insights/archives": ["get"],
        "/api/v1/insights/archives/{origin}/{insight_id}/{archive_id}/restore": [
            "post"
        ],
        "/api/v1/insights/import": ["post"],
        "/api/v1/insights/{origin}/{insight_id}": ["delete", "get"],
    }


def test_store_rejects_corrupt_stored_version_instead_of_guessing(tmp_path: Path) -> None:
    store = _store(tmp_path)
    store.import_document(INSIGHT_YAML)
    stored = store.root / "workshop" / "insight-007" / "v1.yaml"
    payload: dict[str, Any] = yaml.safe_load(stored.read_text(encoding="utf-8"))
    payload["source_text"] = payload["source_text"] + "# tampered\n"
    stored.write_text(
        yaml.safe_dump(payload, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )

    from futures_research.insight.store import InsightStorageError

    with pytest.raises(InsightStorageError):
        store.get("workshop", "insight-007")
    with pytest.raises(InsightStorageError):
        store.list_insights()
